import type { Lesson } from '../types';

export const GAME_LESSONS: Lesson[] = [
  // ══════════ GAME 1: Guess the Number (console) ══════════
  {
    id: 'game-guess-js',
    order: 29,
    title: 'Game: Guess the Number (JS)',
    language: 'javascript',
    instructions:
      'Your first game! Since the terminal can\u2019t take typed input mid-run, the "player" will be a list of guesses we feed in — the game logic is the real lesson here, and it\u2019s the same logic every guessing game uses.\n\nNEW TOOL: Math.random() gives a random decimal between 0 and 1. To get a whole number from 1 to 10:\n\nconst secret = Math.floor(Math.random() * 10) + 1;\n\n(Math.floor chops off decimals; the * 10 scales it; the + 1 shifts 0-9 to 1-10.)\n\nBut random secrets can\u2019t be auto-checked, so for THIS assignment the secret is fixed at 7 — swap in the random line afterward in the sandbox to play for real.\n\nNEW TOOL: break exits a loop immediately. Perfect for "stop once they\u2019ve won."\n\nfor (const g of guesses) {\n  if (g === secret) {\n    // win! then break\n  }\n}\n\nYOUR TASK\nThe starter has secret = 7 and a guesses array. Loop over the guesses. For each one print:\n- "Too low" if the guess is under the secret\n- "Too high" if over\n- "You got it in N tries!" if equal — then break\n\nTrack the try count with a counter that increases every loop pass (start attempts at 0 and ++ it at the top of the loop).\n\nExpected output:\nToo low\nToo high\nToo low\nYou got it in 4 tries!',
    starterCode:
      'const secret = 7;\nconst guesses = [3, 9, 5, 7];\nlet attempts = 0;\n\nfor (const g of guesses) {\n  attempts++;\n  // compare g to secret: too low / too high / win + break\n}\n',
    expectedOutput: ['Too low', 'Too high', 'Too low', 'You got it in 4 tries!'],
  },
  {
    id: 'game-guess-py',
    order: 30,
    title: 'Game: Guess the Number (Python)',
    language: 'python',
    instructions:
      'Same game, Python spelling — a perfect translation exercise.\n\nThe pieces map one-to-one:\n- for g in guesses:  replaces the JS for...of\n- elif replaces else if\n- break works identically\n- attempts += 1 (Python has no ++ operator!)\n- f-strings for the win message\n\nRandom numbers in Python, for when you play in the sandbox later:\n\nimport random\nsecret = random.randint(1, 10)   # inclusive on both ends\n\n(import loads a module — Python\u2019s standard library ships with dice, dates, math and much more. randint is friendlier than the JS dance: both ends included, no flooring.)\n\nYOUR TASK\nSecret is fixed at 7 again. Loop the guesses and print:\n- "Too low" / "Too high" / "You got it in N tries!" then break\n\nExpected output:\nToo low\nToo high\nToo low\nYou got it in 4 tries!',
    starterCode:
      'secret = 7\nguesses = [3, 9, 5, 7]\nattempts = 0\n\nfor g in guesses:\n    attempts += 1\n    # compare g to secret\n',
    expectedOutput: ['Too low', 'Too high', 'Too low', 'You got it in 4 tries!'],
  },

  // ══════════ GAME 2: Clicker (first web game, staged) ══════════
  {
    id: 'game-clicker-1',
    order: 31,
    title: 'Clicker Game 1: The Page',
    language: 'javascript',
    kind: 'web',
    instructions:
      'Time to escape the terminal. From here on you write COMPLETE WEB PAGES, and the output pane becomes a live browser — your games will be genuinely playable.\n\nA web page is an HTML document. HTML is a tree of TAGS:\n\n<!DOCTYPE html>\n<html>\n<head>\n  <title>My Game</title>\n</head>\n<body>\n  <h1>Hello</h1>\n  <p>Some text</p>\n</body>\n</html>\n\n- <head> holds invisible setup (title, styles)\n- <body> holds everything visible\n- <h1> is a big heading, <p> a paragraph, <button> a clickable button\n- Most tags open <p> and close </p> around their content\n\nTwo tags matter most for games:\n\n<button>Click me</button>\n<div id="score">0</div>\n\nA div is a plain box for anything. The id attribute gives an element a unique name so JavaScript can find it later — that\u2019s the bridge between HTML and code, coming next lesson.\n\nYOUR TASK\nBuild the skeleton of a cookie-clicker style game. In the body:\n1. An <h1> that says: Cookie Clicker\n2. A div with id="score" containing 0\n3. A <button> with id="clicker" that says: Click!\n\nHit Run to see your page render. The check looks for all three elements.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Cookie Clicker</title>\n</head>\n<body>\n  <!-- your h1, score div, and button here -->\n</body>\n</html>\n',
    webCheck:
      "document.querySelector('h1') !== null && document.querySelector('#score') !== null && document.querySelector('#clicker') !== null",
  },
  {
    id: 'game-clicker-2',
    order: 32,
    title: 'Clicker Game 2: Making It Work',
    language: 'javascript',
    kind: 'web',
    instructions:
      'Now the magic: JavaScript lives inside a page via the <script> tag (put it at the END of the body, so the elements exist before the code runs):\n\n<body>\n  ...elements...\n  <script>\n    // your JavaScript here\n  </script>\n</body>\n\nTHE THREE MOVES OF ALL WEB GAMES:\n\n1. FIND an element:\n   const btn = document.querySelector("#clicker");\n   (querySelector takes "#name" for ids — same # as CSS)\n\n2. LISTEN for events:\n   btn.addEventListener("click", () => {\n     // runs every time the button is clicked\n   });\n   The () => { } is an ARROW FUNCTION — a compact unnamed function. Read it as "when clicked, do this."\n\n3. CHANGE the page:\n   scoreDiv.textContent = score;\n   (textContent is the text inside an element — read it or overwrite it)\n\nThat\u2019s the whole loop: find, listen, change. Every game from Clicker to Snake is these three moves arranged differently.\n\nYOUR TASK\nStarting from your page (starter includes it):\n1. In a script at the end of body, create let score = 0\n2. Find the button and the score div\n3. On button click: increase score by 1 and write it into the score div\n\nRun it, then CLICK YOUR BUTTON and watch the number climb. The check verifies clicking actually increments the score.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Cookie Clicker</title>\n</head>\n<body>\n  <h1>Cookie Clicker</h1>\n  <div id="score">0</div>\n  <button id="clicker">Click!</button>\n\n  <script>\n    let score = 0;\n    // find elements, add click listener, update score + display\n  </script>\n</body>\n</html>\n',
    webCheck:
      "(function(){ var b=document.querySelector('#clicker'); var s=document.querySelector('#score'); if(!b||!s) return false; var before=s.textContent; b.click(); b.click(); return s.textContent.trim()==='2' || (parseInt(s.textContent)===parseInt(before)+2); })()",
  },
  {
    id: 'game-clicker-3',
    order: 33,
    title: 'Clicker Game 3: Style and Juice',
    language: 'javascript',
    kind: 'web',
    instructions:
      'A working game deserves to look like one. CSS (styles) lives in a <style> tag in the head:\n\n<style>\n  body {\n    background: #1a1a2e;\n    color: white;\n    font-family: sans-serif;\n    text-align: center;\n  }\n  button {\n    font-size: 24px;\n    padding: 16px 32px;\n    border-radius: 12px;\n    cursor: pointer;\n  }\n</style>\n\nEach block is selector { property: value; } — "make body elements have this background," etc. Selectors: tag names select all of that tag, #name selects the element with that id.\n\nGames also love "juice" — small rewards for interaction. Two easy ones:\n\nMILESTONES (you know if/else already):\nif (score === 10) {\n  msg.textContent = "10! You\u2019re on fire!";\n}\n\nGROWING TEXT:\nscoreDiv.style.fontSize = (20 + score) + "px";\n(Any CSS property can be set from JS via .style)\n\nYOUR TASK\nUpgrade your clicker:\n1. Add a <style> block: give the body a background color, centered text, and make the button big and rounded\n2. Add a div with id="msg" to the body\n3. In the script: when score reaches exactly 10, put the text "On fire!" into the msg div\n\nThe check clicks your button 10 times and looks for the message. This one is yours to decorate — colors and fonts are all you.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Cookie Clicker</title>\n  <style>\n    /* your styles */\n  </style>\n</head>\n<body>\n  <h1>Cookie Clicker</h1>\n  <div id="score">0</div>\n  <div id="msg"></div>\n  <button id="clicker">Click!</button>\n\n  <script>\n    let score = 0;\n    const btn = document.querySelector("#clicker");\n    const scoreDiv = document.querySelector("#score");\n    const msg = document.querySelector("#msg");\n\n    btn.addEventListener("click", () => {\n      score++;\n      scoreDiv.textContent = score;\n      // milestone check here\n    });\n  </script>\n</body>\n</html>\n',
    webCheck:
      "(function(){ var b=document.querySelector('#clicker'); var m=document.querySelector('#msg'); if(!b||!m) return false; for(var i=0;i<10;i++){ b.click(); } return m.textContent.toLowerCase().indexOf('fire')!==-1; })()",
  },
  // ══════════ GAME 3: Snake (canvas, staged) ══════════
  {
    id: 'game-snake-1',
    order: 34,
    title: 'Snake 1: The Canvas',
    language: 'javascript',
    kind: 'web',
    instructions:
      'Buttons and divs got us a clicker, but real 2D games draw pixels. Meet <canvas> — a blank rectangle you paint with JavaScript:\n\n<canvas id="game" width="300" height="300"></canvas>\n\nTo draw on it, you grab its CONTEXT — the object holding all the drawing tools:\n\nconst canvas = document.querySelector("#game");\nconst ctx = canvas.getContext("2d");\n\nThen paint rectangles:\n\nctx.fillStyle = "lime";        // choose a color\nctx.fillRect(x, y, width, height);   // paint a rectangle\n\nCanvas coordinates start at the TOP-LEFT corner: x grows rightward, y grows DOWNWARD (this surprises everyone — it\u2019s upside-down from math class).\n\nSnake lives on a GRID. Our canvas is 300×300 and we\u2019ll use 15×15 cells of 20 pixels each. Converting a grid cell to pixels is just multiplication:\n\nconst CELL = 20;\nctx.fillRect(col * CELL, row * CELL, CELL, CELL);   // paints cell (col, row)\n\nYOUR TASK\n1. The starter has the canvas and context ready. Paint the whole canvas black first:\n   ctx.fillStyle = "black"; ctx.fillRect(0, 0, 300, 300);\n2. Then paint a lime cell at grid position column 7, row 7 (the center)\n3. And a red cell at column 3, row 10\n\nRun it — you should see a black board with a lime square and a red square. That red square will be food someday.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Snake</title>\n  <style>\n    body { background: #1a1a2e; display: flex; justify-content: center; padding-top: 20px; }\n    canvas { border: 2px solid #444; }\n  </style>\n</head>\n<body>\n  <canvas id="game" width="300" height="300"></canvas>\n\n  <script>\n    const canvas = document.querySelector("#game");\n    const ctx = canvas.getContext("2d");\n    const CELL = 20;\n\n    // 1. paint the board black\n    // 2. lime cell at col 7, row 7\n    // 3. red cell at col 3, row 10\n  </script>\n</body>\n</html>\n',
    webCheck:
      "(function(){ var c=document.querySelector('#game'); if(!c) return false; var ctx=c.getContext('2d'); var center=ctx.getImageData(7*20+10,7*20+10,1,1).data; var food=ctx.getImageData(3*20+10,10*20+10,1,1).data; var corner=ctx.getImageData(1,1,1,1).data; var isLime=center[1]>150&&center[0]<150; var isRed=food[0]>150&&food[1]<100; var isDark=corner[0]<60&&corner[1]<60&&corner[2]<60; return isLime&&isRed&&isDark; })()",
  },
  {
    id: 'game-snake-2',
    order: 35,
    title: 'Snake 2: Movement and the Game Loop',
    language: 'javascript',
    kind: 'web',
    instructions:
      'Games feel alive because of the GAME LOOP: a function that runs over and over, many times per second, each time updating positions and redrawing everything from scratch.\n\nsetInterval(tick, 150);   // call tick() every 150 milliseconds\n\nfunction tick() {\n  // 1. move things\n  // 2. wipe the canvas\n  // 3. redraw everything\n}\n\nWipe-and-redraw feels wasteful but it\u2019s how every 2D game works — like a flipbook, each frame drawn fresh.\n\nThe snake itself is an ARRAY of segments, each an object with a col and row. The head is index 0:\n\nlet snake = [{ col: 7, row: 7 }];\nlet dir = { col: 1, row: 0 };   // moving right: col +1 per tick\n\nMOVING = add a new head one cell ahead, remove the tail:\n\nconst head = { col: snake[0].col + dir.col, row: snake[0].row + dir.row };\nsnake.unshift(head);   // unshift = push onto the FRONT\nsnake.pop();           // pop = remove from the END\n\nSTEERING = listen for arrow keys on the whole page:\n\ndocument.addEventListener("keydown", (e) => {\n  if (e.key === "ArrowUp") dir = { col: 0, row: -1 };\n  // ...and the other three arrows\n});\n\n(Remember: up is row MINUS one — y grows downward.)\n\nYOUR TASK\nComplete the tick function and the key listener in the starter:\n1. In tick: build the new head from dir, unshift it, pop the tail\n2. Wipe the board black, then draw every segment lime with a for...of loop\n3. In the key listener: handle all four arrow keys\n\nRun it — your square glides right. Click the canvas once (to give it focus), then steer with arrows. It runs off the edge and disappears; walls come in lesson 4.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Snake</title>\n  <style>\n    body { background: #1a1a2e; display: flex; justify-content: center; padding-top: 20px; }\n    canvas { border: 2px solid #444; }\n  </style>\n</head>\n<body>\n  <canvas id="game" width="300" height="300"></canvas>\n\n  <script>\n    const canvas = document.querySelector("#game");\n    const ctx = canvas.getContext("2d");\n    const CELL = 20;\n\n    let snake = [{ col: 7, row: 7 }];\n    let dir = { col: 1, row: 0 };\n\n    document.addEventListener("keydown", (e) => {\n      // set dir for ArrowUp, ArrowDown, ArrowLeft, ArrowRight\n    });\n\n    function tick() {\n      // 1. new head from dir, unshift, pop\n      // 2. wipe black\n      // 3. draw each segment lime\n    }\n\n    setInterval(tick, 150);\n  </script>\n</body>\n</html>\n',
    webCheck:
      "(function(){ if(typeof snake==='undefined'||typeof tick!=='function') return false; var startCol=snake[0].col; tick(); tick(); return snake[0].col===startCol+2*dir.col||snake[0].row!==7; })()",
  },
  {
    id: 'game-snake-3',
    order: 36,
    title: 'Snake 3: Food and Growing',
    language: 'javascript',
    kind: 'web',
    instructions:
      'Now the snake eats. Three additions:\n\nFOOD is just a position, placed randomly on the 15×15 grid:\n\nlet food = randomFood();\n\nfunction randomFood() {\n  return {\n    col: Math.floor(Math.random() * 15),\n    row: Math.floor(Math.random() * 15),\n  };\n}\n\nEATING is a comparison in tick, right after building the new head: if the head landed on the food, the snake GROWS. And here\u2019s the elegant trick — growing means simply NOT popping the tail that turn:\n\nsnake.unshift(head);\nif (head.col === food.col && head.row === food.row) {\n  score++;\n  food = randomFood();   // respawn elsewhere\n} else {\n  snake.pop();           // only shrink when nothing was eaten\n}\n\n(That && is the AND operator — true only when BOTH sides are true. Its sibling || is OR.)\n\nSCORE goes in a div above the canvas, updated the same way as the clicker: scoreDiv.textContent = score.\n\nYOUR TASK\nStarting from your lesson-2 code (starter includes a working version):\n1. Add the food variable and randomFood function\n2. In tick: implement eat-or-pop as shown, and draw the food red each frame\n3. Add a score div (id="score") above the canvas and keep it updated\n\nRun and play — chase the red square, watch yourself grow and the score climb.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Snake</title>\n  <style>\n    body { background: #1a1a2e; color: white; font-family: sans-serif; display: flex; flex-direction: column; align-items: center; padding-top: 12px; }\n    canvas { border: 2px solid #444; }\n  </style>\n</head>\n<body>\n  <div id="score">0</div>\n  <canvas id="game" width="300" height="300"></canvas>\n\n  <script>\n    const canvas = document.querySelector("#game");\n    const ctx = canvas.getContext("2d");\n    const scoreDiv = document.querySelector("#score");\n    const CELL = 20;\n\n    let snake = [{ col: 7, row: 7 }];\n    let dir = { col: 1, row: 0 };\n    let score = 0;\n    // let food = randomFood();\n\n    // function randomFood() { ... }\n\n    document.addEventListener("keydown", (e) => {\n      if (e.key === "ArrowUp") dir = { col: 0, row: -1 };\n      if (e.key === "ArrowDown") dir = { col: 0, row: 1 };\n      if (e.key === "ArrowLeft") dir = { col: -1, row: 0 };\n      if (e.key === "ArrowRight") dir = { col: 1, row: 0 };\n    });\n\n    function tick() {\n      const head = { col: snake[0].col + dir.col, row: snake[0].row + dir.row };\n      snake.unshift(head);\n      // eat-or-pop goes here (replace the plain pop below)\n      snake.pop();\n\n      ctx.fillStyle = "black";\n      ctx.fillRect(0, 0, 300, 300);\n      // draw food red here\n      ctx.fillStyle = "lime";\n      for (const seg of snake) {\n        ctx.fillRect(seg.col * CELL, seg.row * CELL, CELL, CELL);\n      }\n    }\n\n    setInterval(tick, 150);\n  </script>\n</body>\n</html>\n',
    webCheck:
      "(function(){ if(typeof snake==='undefined'||typeof food==='undefined'||typeof randomFood!=='function'||typeof tick!=='function') return false; food={col:snake[0].col+dir.col,row:snake[0].row+dir.row}; var lenBefore=snake.length; var scoreBefore=score; tick(); return snake.length===lenBefore+1&&score===scoreBefore+1; })()",
  },
  {
    id: 'game-snake-4',
    order: 37,
    title: 'Snake 4: Death and Game Over',
    language: 'javascript',
    kind: 'web',
    instructions:
      'A game you can\u2019t lose is a screensaver. Two ways to die in Snake:\n\n1. HITTING A WALL — the new head leaves the 15×15 grid:\n\nif (head.col < 0 || head.col > 14 || head.row < 0 || head.row > 14) {\n  return gameOver();\n}\n\n2. HITTING YOURSELF — the new head lands on an existing segment. Arrays have a perfect method for "does any item match?":\n\nconst hitSelf = snake.some(seg => seg.col === head.col && seg.row === head.row);\nif (hitSelf) return gameOver();\n\n(.some runs your arrow function against each item and returns true if ANY passes. Check this BEFORE unshifting the new head.)\n\nGAME OVER stops the loop. setInterval returns an id you can cancel:\n\nconst timer = setInterval(tick, 150);\n\nfunction gameOver() {\n  clearInterval(timer);\n  ctx.fillStyle = "white";\n  ctx.font = "30px sans-serif";\n  ctx.fillText("Game Over", 70, 150);   // draws text at x, y\n}\n\nThe return before gameOver() matters — it exits tick immediately so the dead snake doesn\u2019t keep moving that frame.\n\nYOUR TASK\nStarting from your lesson-3 game (starter has it complete):\n1. Store the interval id in a const timer\n2. At the TOP of tick, after computing head: wall check, then self check — each returning gameOver()\n3. Write gameOver: stop the timer, draw "Game Over" on the canvas\n\nRun it and play a full game: eat, grow, steer, and finally crash. You\u2019ve built Snake — the same game that shipped on a billion Nokia phones — from an empty canvas.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Snake</title>\n  <style>\n    body { background: #1a1a2e; color: white; font-family: sans-serif; display: flex; flex-direction: column; align-items: center; padding-top: 12px; }\n    canvas { border: 2px solid #444; }\n  </style>\n</head>\n<body>\n  <div id="score">0</div>\n  <canvas id="game" width="300" height="300"></canvas>\n\n  <script>\n    const canvas = document.querySelector("#game");\n    const ctx = canvas.getContext("2d");\n    const scoreDiv = document.querySelector("#score");\n    const CELL = 20;\n\n    let snake = [{ col: 7, row: 7 }];\n    let dir = { col: 1, row: 0 };\n    let score = 0;\n    let food = randomFood();\n\n    function randomFood() {\n      return {\n        col: Math.floor(Math.random() * 15),\n        row: Math.floor(Math.random() * 15),\n      };\n    }\n\n    document.addEventListener("keydown", (e) => {\n      if (e.key === "ArrowUp") dir = { col: 0, row: -1 };\n      if (e.key === "ArrowDown") dir = { col: 0, row: 1 };\n      if (e.key === "ArrowLeft") dir = { col: -1, row: 0 };\n      if (e.key === "ArrowRight") dir = { col: 1, row: 0 };\n    });\n\n    function tick() {\n      const head = { col: snake[0].col + dir.col, row: snake[0].row + dir.row };\n\n      // 1. wall check → return gameOver()\n      // 2. self check with .some → return gameOver()\n\n      snake.unshift(head);\n      if (head.col === food.col && head.row === food.row) {\n        score++;\n        scoreDiv.textContent = score;\n        food = randomFood();\n      } else {\n        snake.pop();\n      }\n\n      ctx.fillStyle = "black";\n      ctx.fillRect(0, 0, 300, 300);\n      ctx.fillStyle = "red";\n      ctx.fillRect(food.col * CELL, food.row * CELL, CELL, CELL);\n      ctx.fillStyle = "lime";\n      for (const seg of snake) {\n        ctx.fillRect(seg.col * CELL, seg.row * CELL, CELL, CELL);\n      }\n    }\n\n    const timer = setInterval(tick, 150);\n\n    // function gameOver() { ... }\n  </script>\n</body>\n</html>\n',
    webCheck:
      "(function(){ if(typeof tick!=='function'||typeof gameOver!=='function'||typeof snake==='undefined') return false; snake=[{col:14,row:7}]; dir={col:1,row:0}; var lenBefore=1; tick(); return snake.length===lenBefore; })()",
  },
  // ══════════ GAME 4: Breakout (canvas physics, staged) ══════════
  {
    id: 'game-breakout-1',
    order: 38,
    title: 'Breakout 1: A Bouncing Ball',
    language: 'javascript',
    kind: 'web',
    instructions:
      'Snake moved on a grid, one cell per tick. Breakout introduces smooth PIXEL movement — the foundation of physics in games.\n\nA moving ball is a position plus a VELOCITY (speed and direction):\n\nlet ball = { x: 150, y: 200, vx: 3, vy: -3 };\n\nvx and vy are "how many pixels to move per frame." Each tick:\n\nball.x += ball.vx;\nball.y += ball.vy;\n\nWith vx 3 and vy -3, the ball drifts right and up (negative y is up, remember). At 60 frames per second that\u2019s smooth motion.\n\nBOUNCING is one beautiful trick: when the ball hits a wall, flip the velocity\u2019s sign:\n\nif (ball.x < 8 || ball.x > 292) ball.vx = -ball.vx;   // side walls\nif (ball.y < 8) ball.vy = -ball.vy;                    // ceiling\n\nGoing right at +3? Now going left at -3. That single sign-flip IS the physics.\n\n(The 8s account for the ball\u2019s radius, so it bounces at its edge, not its center.)\n\nDrawing a circle needs three context calls:\n\nctx.beginPath();\nctx.arc(ball.x, ball.y, 8, 0, Math.PI * 2);   // center x, y, radius, full circle\nctx.fill();\n\nAnd one upgrade from Snake: instead of setInterval we use requestAnimationFrame — the browser\u2019s native "call me before the next screen repaint," giving silky 60fps:\n\nfunction tick() {\n  // move, bounce, draw\n  requestAnimationFrame(tick);   // schedule the next frame\n}\nrequestAnimationFrame(tick);      // kick it off\n\nYOUR TASK\nComplete tick in the starter:\n1. Move the ball by its velocity\n2. Bounce off left, right, and top walls (bottom stays open — that\u2019s where you\u2019ll lose, later)\n3. Wipe the canvas black and draw the ball white\n\nRun it — a ball should ricochet around, escaping only through the floor.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Breakout</title>\n  <style>\n    body { background: #1a1a2e; display: flex; justify-content: center; padding-top: 20px; }\n    canvas { border: 2px solid #444; }\n  </style>\n</head>\n<body>\n  <canvas id="game" width="300" height="400"></canvas>\n\n  <script>\n    const canvas = document.querySelector("#game");\n    const ctx = canvas.getContext("2d");\n\n    let ball = { x: 150, y: 200, vx: 3, vy: -3 };\n\n    function tick() {\n      // 1. move ball by vx, vy\n      // 2. bounce: left/right walls flip vx, ceiling flips vy\n      // 3. wipe black, draw white ball (beginPath, arc, fill)\n\n      requestAnimationFrame(tick);\n    }\n\n    requestAnimationFrame(tick);\n  </script>\n</body>\n</html>\n',
    webCheck:
      "(function(){ if(typeof ball==='undefined'||typeof tick!=='function') return false; ball.x=295; ball.vx=3; var before=ball.vx; tick(); if(ball.vx!==-before) return false; ball.y=5; ball.vy=-3; var vb=ball.vy; tick(); return ball.vy===-vb; })()",
  },
  {
    id: 'game-breakout-2',
    order: 39,
    title: 'Breakout 2: The Paddle',
    language: 'javascript',
    kind: 'web',
    instructions:
      'Time to give the player control. The paddle follows the MOUSE:\n\nlet paddleX = 120;   // left edge of the paddle\nconst PADDLE_W = 60, PADDLE_H = 10;\n\ncanvas.addEventListener("mousemove", (e) => {\n  const rect = canvas.getBoundingClientRect();\n  paddleX = e.clientX - rect.left - PADDLE_W / 2;\n});\n\nBreak that down: e.clientX is the mouse\u2019s position on the SCREEN; getBoundingClientRect tells us where the canvas sits on the screen; subtracting converts to canvas coordinates; and subtracting half the paddle width centers the paddle under the cursor.\n\nBonus for phones — the same idea with touch:\n\ncanvas.addEventListener("touchmove", (e) => {\n  e.preventDefault();\n  const rect = canvas.getBoundingClientRect();\n  paddleX = e.touches[0].clientX - rect.left - PADDLE_W / 2;\n});\n\nPADDLE COLLISION is a rectangle check — is the ball inside the paddle\u2019s span while moving downward at paddle height?\n\nif (\n  ball.vy > 0 &&\n  ball.y > 385 - 8 &&\n  ball.x > paddleX &&\n  ball.x < paddleX + PADDLE_W\n) {\n  ball.vy = -ball.vy;\n}\n\n(The vy > 0 guard means "only when falling" — otherwise the ball can get glued to the paddle, flipping every frame.)\n\nAnd if the ball passes the paddle and exits the floor, that\u2019s a MISS — for now, just reset it to the center:\n\nif (ball.y > 410) {\n  ball = { x: 150, y: 200, vx: 3, vy: -3 };\n}\n\nYOUR TASK\nStarting from your bouncing ball (starter included):\n1. Add the paddle variables and the mousemove listener (touchmove optional but nice)\n2. In tick: draw the paddle — a white fillRect at y 385, PADDLE_W wide, PADDLE_H tall\n3. Add the paddle bounce and the floor reset\n\nRun it and keep the ball alive with your mouse.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Breakout</title>\n  <style>\n    body { background: #1a1a2e; display: flex; justify-content: center; padding-top: 20px; }\n    canvas { border: 2px solid #444; }\n  </style>\n</head>\n<body>\n  <canvas id="game" width="300" height="400"></canvas>\n\n  <script>\n    const canvas = document.querySelector("#game");\n    const ctx = canvas.getContext("2d");\n\n    let ball = { x: 150, y: 200, vx: 3, vy: -3 };\n    let paddleX = 120;\n    const PADDLE_W = 60, PADDLE_H = 10;\n\n    // mousemove listener here\n\n    function tick() {\n      ball.x += ball.vx;\n      ball.y += ball.vy;\n\n      if (ball.x < 8 || ball.x > 292) ball.vx = -ball.vx;\n      if (ball.y < 8) ball.vy = -ball.vy;\n\n      // paddle bounce here\n      // floor reset here\n\n      ctx.fillStyle = "black";\n      ctx.fillRect(0, 0, 300, 400);\n      ctx.fillStyle = "white";\n      ctx.beginPath();\n      ctx.arc(ball.x, ball.y, 8, 0, Math.PI * 2);\n      ctx.fill();\n      // draw paddle here\n\n      requestAnimationFrame(tick);\n    }\n\n    requestAnimationFrame(tick);\n  </script>\n</body>\n</html>\n',
    webCheck:
      "(function(){ if(typeof ball==='undefined'||typeof paddleX==='undefined'||typeof tick!=='function') return false; paddleX=120; ball={x:150,y:379,vx:0,vy:4}; tick(); if(ball.vy>=0) return false; ball={x:150,y:415,vx:3,vy:3}; tick(); return ball.y>=150&&ball.y<=260; })()",
  },
  {
    id: 'game-breakout-3',
    order: 40,
    title: 'Breakout 3: Bricks',
    language: 'javascript',
    kind: 'web',
    instructions:
      'The finale: bricks to smash. This lesson combines everything — nested loops, arrays of objects, collision, score, and win/lose states.\n\nBUILDING THE WALL uses a nested loop — a loop inside a loop, the standard way to generate grids:\n\nlet bricks = [];\nfor (let row = 0; row < 4; row++) {\n  for (let col = 0; col < 6; col++) {\n    bricks.push({ x: col * 50, y: row * 20 + 30, alive: true });\n  }\n}\n\nThe outer loop runs 4 times; for EACH of those, the inner runs 6 times — 24 bricks, each 50×20 pixels, positioned by its row and column. The alive flag is how we "destroy" a brick without the headache of removing it from the array mid-loop: dead bricks just stop being drawn or checked.\n\nBRICK COLLISION, inside tick, checks the ball against every living brick:\n\nfor (const b of bricks) {\n  if (!b.alive) continue;   // continue = skip to the next loop item\n  if (ball.x > b.x && ball.x < b.x + 50 && ball.y > b.y && ball.y < b.y + 20) {\n    b.alive = false;\n    ball.vy = -ball.vy;\n    score++;\n  }\n}\n\nDRAWING skips dead bricks the same way, and a per-row color makes it pretty:\n\nconst colors = ["#f85149", "#f0883e", "#3fb950", "#58a6ff"];\nctx.fillStyle = colors[Math.floor((b.y - 30) / 20)];\nctx.fillRect(b.x + 1, b.y + 1, 48, 18);   // +1/-2 leaves a gap between bricks\n\nWINNING: after the collision loop, if score === 24, draw "You Win!" and stop (a gameOver-style function with a stop flag works — see starter).\n\nYOUR TASK\nComplete the starter:\n1. Build the 24-brick wall with a nested loop\n2. Add brick collision with score\n3. Draw living bricks in row colors, plus the score text (ctx.fillText at the bottom corner)\n4. Win at 24, lose is already handled (3 missed balls ends the game)\n\nRun it and clear the wall. When you finish this one, you\u2019ve independently implemented one of the most famous games ever made — Steve Wozniak built the original Breakout hardware for Atari before co-founding Apple.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Breakout</title>\n  <style>\n    body { background: #1a1a2e; display: flex; justify-content: center; padding-top: 20px; }\n    canvas { border: 2px solid #444; }\n  </style>\n</head>\n<body>\n  <canvas id="game" width="300" height="400"></canvas>\n\n  <script>\n    const canvas = document.querySelector("#game");\n    const ctx = canvas.getContext("2d");\n\n    let ball = { x: 150, y: 250, vx: 3, vy: -3 };\n    let paddleX = 120;\n    const PADDLE_W = 60, PADDLE_H = 10;\n    let score = 0;\n    let lives = 3;\n    let stopped = false;\n\n    let bricks = [];\n    // nested loop: 4 rows, 6 cols, 50x20 bricks starting at y 30\n\n    canvas.addEventListener("mousemove", (e) => {\n      const rect = canvas.getBoundingClientRect();\n      paddleX = e.clientX - rect.left - PADDLE_W / 2;\n    });\n\n    function endGame(text) {\n      stopped = true;\n      ctx.fillStyle = "white";\n      ctx.font = "30px sans-serif";\n      ctx.fillText(text, 75, 200);\n    }\n\n    function tick() {\n      if (stopped) return;\n\n      ball.x += ball.vx;\n      ball.y += ball.vy;\n\n      if (ball.x < 8 || ball.x > 292) ball.vx = -ball.vx;\n      if (ball.y < 8) ball.vy = -ball.vy;\n\n      if (ball.vy > 0 && ball.y > 377 && ball.x > paddleX && ball.x < paddleX + PADDLE_W) {\n        ball.vy = -ball.vy;\n      }\n\n      if (ball.y > 410) {\n        lives--;\n        if (lives === 0) return endGame("Game Over");\n        ball = { x: 150, y: 250, vx: 3, vy: -3 };\n      }\n\n      // brick collision loop here (set alive false, flip vy, score++)\n      // win check: score === 24 → return endGame("You Win!")\n\n      ctx.fillStyle = "black";\n      ctx.fillRect(0, 0, 300, 400);\n\n      // draw living bricks here (row colors)\n\n      ctx.fillStyle = "white";\n      ctx.beginPath();\n      ctx.arc(ball.x, ball.y, 8, 0, Math.PI * 2);\n      ctx.fill();\n      ctx.fillRect(paddleX, 385, PADDLE_W, PADDLE_H);\n      ctx.font = "14px sans-serif";\n      ctx.fillText("Score: " + score + "  Lives: " + lives, 8, 396);\n\n      requestAnimationFrame(tick);\n    }\n\n    requestAnimationFrame(tick);\n  </script>\n</body>\n</html>\n',
    webCheck:
      "(function(){ if(typeof bricks==='undefined'||!Array.isArray(bricks)||bricks.length!==24||typeof tick!=='function') return false; var b=bricks.find(function(x){return x.alive;}); if(!b) return false; ball={x:b.x+25,y:b.y+10,vx:0,vy:-3}; var s=score; tick(); return b.alive===false&&score===s+1; })()",
  },

  // ══════════ GAME 5: Memory Match (DOM, phone-friendly, staged) ══════════
  {
    id: 'game-memory-1',
    order: 41,
    title: 'Memory Match 1: The Card Grid',
    language: 'javascript',
    kind: 'web',
    instructions:
      'Last game — and this one plays perfectly on phones, because it\u2019s built from tappable DOM elements instead of a keyboard-and-mouse canvas.\n\nMemory Match: 16 face-down cards hiding 8 pairs of emoji. Tap two; if they match they stay revealed, if not they flip back.\n\nBUILDING ELEMENTS FROM CODE is the new skill. Until now your HTML was hand-written; games with many similar pieces generate them:\n\nconst card = document.createElement("div");   // make a div in memory\ncard.className = "card";                        // give it a CSS class\ncard.textContent = "?";\nboard.appendChild(card);                        // attach it to the page\n\n(className connects to a .card { } rule in your styles — the . prefix in CSS means "class," as # means "id." Classes mark MANY elements; ids mark one.)\n\nTHE DECK: 8 emoji, each twice, then shuffled. The classic one-line shuffle:\n\nconst EMOJI = ["🐍", "🎮", "🍪", "🚀", "🐙", "🎲", "🧠", "⭐"];\nlet deck = [...EMOJI, ...EMOJI];               // spread: copies the array twice into one\ndeck.sort(() => Math.random() - 0.5);           // quick shuffle\n\nA GRID LAYOUT in CSS makes 16 cards into a 4×4 board:\n\n#board {\n  display: grid;\n  grid-template-columns: repeat(4, 70px);\n  gap: 8px;\n}\n\nYOUR TASK\n1. In the script: loop over the shuffled deck with for (const emoji of deck), and for each one create a card div (class "card", text "?") and append it to the board\n2. Store each card\u2019s secret: card.dataset.emoji = emoji; — dataset lets you stash custom data on an element for later\n3. In the styles: make #board a 4-column grid and give .card a size (70px square works), centered text, big font-size, pointer cursor, and a background color\n\nRun it — a 4×4 wall of ? tiles. Flipping comes next lesson.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Memory Match</title>\n  <style>\n    body { background: #1a1a2e; color: white; font-family: sans-serif; display: flex; flex-direction: column; align-items: center; padding-top: 16px; }\n    #board {\n      /* grid layout here */\n    }\n    .card {\n      /* size, centering, font, cursor, background */\n    }\n  </style>\n</head>\n<body>\n  <h1>Memory Match</h1>\n  <div id="board"></div>\n\n  <script>\n    const board = document.querySelector("#board");\n    const EMOJI = ["🐍", "🎮", "🍪", "🚀", "🐙", "🎲", "🧠", "⭐"];\n    let deck = [...EMOJI, ...EMOJI];\n    deck.sort(() => Math.random() - 0.5);\n\n    // loop the deck: create each card, set dataset.emoji, append\n  </script>\n</body>\n</html>\n',
    webCheck:
      "(function(){ var cards=document.querySelectorAll('.card'); if(cards.length!==16) return false; var withData=0; cards.forEach(function(c){ if(c.dataset.emoji) withData++; }); return withData===16; })()",
  },
  {
    id: 'game-memory-2',
    order: 42,
    title: 'Memory Match 2: Flip Logic',
    language: 'javascript',
    kind: 'web',
    instructions:
      'The final lesson of the curriculum. The flip logic is a genuinely interesting puzzle — a small STATE MACHINE, which is a fancy name for "a variable tracking what phase we\u2019re in, and rules for moving between phases."\n\nOur state: let flipped = []; — the cards currently face-up and unresolved (0, 1, or 2 of them).\n\nWhen a card is clicked:\n\n1. GUARDS first — ignore the click if:\n   - the card is already revealed (check a class or dataset flag)\n   - two cards are already flipped and being judged\n   card.classList.contains("done")  /  flipped.length === 2\n\n2. REVEAL — show the emoji: card.textContent = card.dataset.emoji; and push the card into flipped.\n\n3. JUDGE — when flipped reaches 2:\n   - MATCH (both dataset.emoji equal): mark both with classList.add("done"), empty the array (flipped = []), and count the pair\n   - NO MATCH: flip them back — but not instantly, or the player never sees the second card. Delay with setTimeout:\n\n     setTimeout(() => {\n       flipped[0].textContent = "?";\n       flipped[1].textContent = "?";\n       flipped = [];\n     }, 800);\n\n   (setTimeout runs a function ONCE after a delay — setInterval\u2019s one-shot sibling. The 800ms pause is why the flipped.length === 2 guard exists: it blocks clicking a third card during the peek.)\n\n4. WIN — when all 8 pairs are found, show a victory message in the status div.\n\nAdd a .done style so matched cards look settled — a different background, maybe reduced opacity.\n\nYOUR TASK\nThe starter has your grid plus a status div. Wire the click listener on each card as it\u2019s created (inside the deck loop) implementing all four steps. Track pairs in let pairs = 0 and show "You win!" in #status when pairs reaches 8.\n\nRun it and play. Then hand your phone to someone and watch them play a game you built from nothing. That\u2019s the whole journey — 42 lessons from console.log("Hello, World!") to here.',
    starterCode:
      '<!DOCTYPE html>\n<html>\n<head>\n  <title>Memory Match</title>\n  <style>\n    body { background: #1a1a2e; color: white; font-family: sans-serif; display: flex; flex-direction: column; align-items: center; padding-top: 16px; }\n    #board { display: grid; grid-template-columns: repeat(4, 70px); gap: 8px; }\n    .card { width: 70px; height: 70px; display: flex; align-items: center; justify-content: center; font-size: 32px; cursor: pointer; background: #30363d; border-radius: 8px; user-select: none; }\n    .done { background: #1f6feb33; opacity: 0.7; }\n  </style>\n</head>\n<body>\n  <h1>Memory Match</h1>\n  <div id="status"></div>\n  <div id="board"></div>\n\n  <script>\n    const board = document.querySelector("#board");\n    const status = document.querySelector("#status");\n    const EMOJI = ["🐍", "🎮", "🍪", "🚀", "🐙", "🎲", "🧠", "⭐"];\n    let deck = [...EMOJI, ...EMOJI];\n    deck.sort(() => Math.random() - 0.5);\n\n    let flipped = [];\n    let pairs = 0;\n\n    for (const emoji of deck) {\n      const card = document.createElement("div");\n      card.className = "card";\n      card.textContent = "?";\n      card.dataset.emoji = emoji;\n\n      card.addEventListener("click", () => {\n        // guards, reveal, judge, win — your state machine here\n      });\n\n      board.appendChild(card);\n    }\n  </script>\n</body>\n</html>\n',
    webCheck:
      "(function(){ var cards=Array.from(document.querySelectorAll('.card')); if(cards.length!==16) return false; var byEmoji={}; cards.forEach(function(c){ (byEmoji[c.dataset.emoji]=byEmoji[c.dataset.emoji]||[]).push(c); }); var pair=Object.values(byEmoji).find(function(p){return p.length===2;}); if(!pair) return false; pair[0].click(); pair[1].click(); return pair[0].classList.contains('done')&&pair[1].classList.contains('done')&&pair[0].textContent!=='?'; })()",
  },
];
